config:

  lang: ru

  integrations:
    WorldGuard: false
    MythicMobs: false
    PlaceholderAPI: true

  # Сезонные хар-ки
  season:
    # Включить или нет
    enable: false
    # Плейсхолдер сезона
    papi: '%draimfishing_season%'

  # Если в определенном месте нет кастомной рыбы, может ли
  # игрок получить ванильную рыбу во время рыбалки?
  # Если установлено значение false, то игрок не сможет поймать какие-либо ванильные предметы.
  # Вы также можете записать ванильную рыбу или лут в рыбалку(прямо в этот плуг)
  vanilla-loot-when-no-custom-fish: false

  # Кастомную рыбу можно ловить только в открытых водоемах
  need-open-water: true

  # Может ли только удочка из этого плагина ловить рыбу?
  need-special-rod: false

  # Показатель успеха
  # Вы можете настроить количество областей, что дает возможность настраивать пользовательский интерфейс
  success-rate:
    bar1:
      # Кол-во пикселей в каждом интервале
      # Конфигурация по умолчанию составляет 16 пикселей на интервал
      # Если вы заинтересованы в настройке пользовательского интерфейса, рекомендуется обратиться к гусю за помощью
      range: 16
      title: 'Рыба попалась на крючок, обратите внимание!'
      subtitle:
        start: '<font:draimfishing:bar>'
        bar: '뀄'
        pointer_offset: '뀂'
        pointer: '뀃'
        offset: '뀁'
        end: '</font>'
      layout:
        1: 0
        2: 0
        3: 0
        4: 0.1
        5: 0.5
        6: 1
        7: 0.5
        8: 0.1
        9: 0
        10: 0
        11: 0
    bar2:
      range: 8
      title: 'Рыба попалась на крючок, обратите внимание!'
      subtitle:
        start: '<font:draimfishing:bar1>'
        bar: '뀅'
        pointer_offset: '뀂'
        pointer: '뀃'
        offset: '뀁'
        end: '</font>'
      layout:
        1: 0
        2: 0
        3: 0
        4: 0
        5: 0
        6: 0
        7: 0.1
        8: 0.1
        9: 0.3
        10: 0.3
        11: 1
        12: 0.3
        13: 0.1
        14: 0
        15: 0.1
        16: 0.3
        17: 1
        18: 0.3
        19: 0.1
        20: 0
        21: 0
        22: 0

  # Время перезарядки при использовании поиска рыбы (мс)
  fishfinder-cooldown: 3000

  # Изменение времени, необходимое для рыбалки
  # Мин и Макс значение времени должно быть указано в paper.yml
  time-multiply: 2