name: DraimFishing
version: '${version}'
main: net.draimcido.draimfishing.Main
api-version: 1.19
authors: [ DraimGooSe ]
softdepend:
  - MysticMobs
  - PlaceholderAPI
  - WorldGuard
  - mcMMO
  - AureliumSkills
  - MMOCore
  - EcoSkills
  - RealisticSeasons
  - DraimFarming
commands:
  draimfishing:
    usage: /draimfishing
    description: Main command.
    permission: draimfishing.admin
    aliases: dfishing
