simple_bait:
  material: paper
  display:
    name: '<gray>Common fishing lures'
    lore:
      - '<white>Reduce the time spent fishing'
      - '<white>But make it more difficult to catch fish'
  custom-model-data: 646
  # Bait Modifier
  modifier:
    # Change the loot weight of the specified group
    # Add or subtract weights
    weight-PM:
      silver: 5
      gold: 3
    # Multiply or divide weights
    weight-MQ:
      silver: 1.1
      gold: 1.1
    # Change the time to fish (>1 for longer, <1 for shorter)
    time: 0.85
    # Change the difficulty, for example, if the original difficulty is (1-6), now it becomes (1-9)
    difficulty: 3
    # Double loot probability
    double-loot: 0.06
    # Multiply the score got in competition
    score: 1.2

wild_bait:
  material: paper
  display:
    name: 'Wild Bait'
    lore:
      - '<white>Decreases fishing time by 30%.'
  custom-model-data: 696
  modifier:
    time: 0.7

magnet_bait:
  material: paper
  display:
    name: '<gray>Magnet Bait'
    lore:
      - '<white>Increases the probability of better loot by 15%.'
  custom-model-data: 695
  modifier:
    weight-MQ:
      silver: 1.15
      gold: 1.15